### ISSUE TITLE
Emergency! Banana split in the repository!

### ISSUE THREAD

**Issue by kjellberg** [FreshBananas/banana#1]
We just discovered that the repository has suffered a serious banana split! The ascii image of the banana that was the centerpiece of this repository has been sliced in half and we don't know how to fix it.

             ____                           ___
            |  _ \  ___              _   _.' _ `.
         _  | [_) )' _ `._           _  ___ ! \ | | (_) |    _
        |:;.|  _ <| (_) | \ |        |' _ `|  \| |  _  |  .:;|
        |   `.[_) )  _  |  \|        | (_) |     | | | |.',..|
        ':.   `. /| | | |     |         _  | |\  | | |.' :;::'
         !::,   `-!_| | | |\         | | | | | \ !_!.'   ':;!
         !::;       ":;:!.!.\_       !_!_!.!-'-':;:''    '''!
         ';:'        `::;::;'                    ''     .,  .
           `:     .,.    `'           .::... .      .::;::;'
             `..:;::;:..             ::;::;:;:;,    :;::;'
               "-:;::;:;:             ':;::;:''     ;.-'
                   ""`---...       ________...---'"" 

We urgently need your help to restore this banana to its former glory. We're appealing to all banana experts out there to lend a hand in this dire situation.

We're not sure how this happened, but we suspect that someone might have accidentally sat on the keyboard or that a rogue monkey may have snuck into the repository and caused chaos. Whatever the cause, we need to fix this and bring our banana back to one piece.

Please, if you have any ideas on how to repair this banana split, we beg you to come forward and help us out. Don't let our banana go to waste - let's peel this problem and restore our repository to its former glory!

Wait, no.. It's just a prank!

We couldn't resist playing a little joke on you. Our repository only contains an ascii image of a whole banana - there's no banana split here. We hope you got a good laugh out of it.

In all seriousness, we appreciate your interest in our repository and hope that you'll stick around to see what we have in store. And who knows, maybe one day we'll actually have a banana split in our repo, but until then, let's just enjoy the whole banana.

**Comment by jeliasson** [comment]
@kjellberg and ChatGPT, two silly gooses!

**Comment by debuglebowski** [comment]
Maybe we could fix this with a monkey patch @jeliasson?
